### ISSUE TITLE
Weird "microsoft" statement

### ISSUE THREAD

**Issue by verdverm** [olympos-labs/pruning-radix-trie#1]
In the readme, you have the following:

> Additionally, the "microsoft" lookup result is a little weird. Both implementations should scan down to the subtrie with the "microsoft" prefix, and there are no children underneath that node in my implementation. Consequently, I would expect identical performance for those (.. well, better if we use trie properties), not an improvement for the pruning radix trie.

You should definitely have nodes under microsoft, you can see there are longer "terms" using grep. I think the issue is that you thought the code was trimming bigrams, but it's actually separating the term from the rank with a tab. There are terms in the bench data that are comprised of multiple words.

Top results (in my implementation, which may or may not be correct yet):

```
Results:
  microsoft corp 20
  microsoft dynamics 10
  microsoft office 31
  microsoft visual 7
  microsoft flight 5
  microsoft live 6
  microsoft lumia 11
  microsoft windows 19
  microsoft 474
  microsoft expression 4
```

**Comment by verdverm** [comment]
With corrected data in your tests/benchmarks...

```
    ptrie_test.go:35: 
    ptrie_test.go:30: matches for microsoft
    ptrie_test.go:33: microsoft: 474
    ptrie_test.go:33: microsoft office: 31
    ptrie_test.go:33: microsoft corp: 20
    ptrie_test.go:33: microsoft windows: 19
    ptrie_test.go:33: microsoft lumia: 11
    ptrie_test.go:33: microsoft dynamics: 10
    ptrie_test.go:33: microsoft visual: 7
    ptrie_test.go:33: microsoft live: 6
    ptrie_test.go:33: microsoft flight: 5
    ptrie_test.go:33: microsoft exchange: 4
    ptrie_test.go:35: 
--- PASS: TestPTrie (4.71s)
```

```
$ go test -bench=.
goos: linux
goarch: amd64
pkg: olympos.io/container/pruning-radix-trie
cpu: 12th Gen Intel(R) Core(TM) i5-1240P
BenchmarkMicrosoft/m-16          1565448               724.3 ns/op
BenchmarkMicrosoft/mi-16         1368033               807.0 ns/op
BenchmarkMicrosoft/mic-16                2119398               556.3 ns/op
BenchmarkMicrosoft/micr-16               2176530               650.4 ns/op
BenchmarkMicrosoft/micro-16              1872166               639.3 ns/op
BenchmarkMicrosoft/micros-16             2760781               493.8 ns/op
BenchmarkMicrosoft/microso-16            3332203               358.4 ns/op
BenchmarkMicrosoft/microsof-16           2923384               348.0 ns/op
BenchmarkMicrosoft/microsoft-16          3423640               386.0 ns/op
PASS
ok      olympos.io/container/pruning-radix-trie 29.497s
```

**Comment by hypirion** [comment]
@verdverm: Thanks for the correction, that was a bit embarrasing. I just looked at the raw file and assumed both elements were tab-separated.

I'll update the repo with that statement removed as well as an updated chart.

**Comment by verdverm** [comment]
I was in the middle of implementing my own, but yours is quite optimized already, those zero allocs are nice.

I have a small change to `result.insert` that looks to bump performance nicely, basically a reverse bubble sort, PR incoming

**Comment by verdverm** [comment]
@hypirion 

fyi, noticing an element out of order in the original code with the updated data

```
    ptrie_test.go:30: matches for microsoft
    ptrie_test.go:33: microsoft: 474
    ptrie_test.go:33: microsoft office: 31
    ptrie_test.go:33: microsoft windows: 19
    ptrie_test.go:33: microsoft lumia: 11
    ptrie_test.go:33: microsoft dynamics: 10
    ptrie_test.go:33: microsoft visual: 7
    ptrie_test.go:33: microsoft live: 6
    ptrie_test.go:33: microsoft flight: 5
    ptrie_test.go:33: microsoft corp: 20               <========= (out of place)
    ptrie_test.go:33: microsoft exchange: 4
```

**Comment by verdverm** [comment]
with `sort.Slice` after the original insert sort

```
    ptrie_test.go:33: microsoft: 474
    ptrie_test.go:33: microsoft office: 31
    ptrie_test.go:33: microsoft corp: 20
    ptrie_test.go:33: microsoft windows: 19
    ptrie_test.go:33: microsoft lumia: 11
    ptrie_test.go:33: microsoft dynamics: 10
    ptrie_test.go:33: microsoft visual: 7
    ptrie_test.go:33: microsoft live: 6
    ptrie_test.go:33: microsoft flight: 5
    ptrie_test.go:33: microsoft exchange: 4
```

**Comment by hypirion** [comment]
> @hypirion
> 
> fyi, noticing an element out of order in the original code with the updated data
> 
> ```
>     ptrie_test.go:30: matches for microsoft
>     ptrie_test.go:33: microsoft: 474
>     ptrie_test.go:33: microsoft office: 31
>     ptrie_test.go:33: microsoft windows: 19
>     ptrie_test.go:33: microsoft lumia: 11
>     ptrie_test.go:33: microsoft dynamics: 10
>     ptrie_test.go:33: microsoft visual: 7
>     ptrie_test.go:33: microsoft live: 6
>     ptrie_test.go:33: microsoft flight: 5
>     ptrie_test.go:33: microsoft corp: 20               <========= (out of place)
>     ptrie_test.go:33: microsoft exchange: 4
> ```

That's a bit weird. I get 

```
    ptrie_test.go:30: matches for microsoft
    ptrie_test.go:33: microsoft: 474
    ptrie_test.go:33: microsoft office: 31
    ptrie_test.go:33: microsoft corp: 20
    ptrie_test.go:33: microsoft windows: 19
    ptrie_test.go:33: microsoft lumia: 11
    ptrie_test.go:33: microsoft dynamics: 10
    ptrie_test.go:33: microsoft visual: 7
    ptrie_test.go:33: microsoft live: 6
    ptrie_test.go:33: microsoft flight: 5
    ptrie_test.go:33: microsoft exchange: 4
```

with [afa9a95](https://github.com/olympos-labs/pruning-radix-trie/commit/afa9a9526e9484f74a80d2837777c4397a4e0373)

**Comment by verdverm** [comment]
yeah, I may have confused what code I was running at the time

I also found a small bug in my original benchmarks, the gains not as great, maybe 10% better now

**Comment by hypirion** [comment]
> yeah, I may have confused what code I was running at the time
> 
> I also found a small bug in my original benchmarks, the gains not as great, maybe 10% better now

Happy to take a look at the improvement regardless! I think there's one that should in theory speed it up a little bit, but I'm sure there are quite a bit of other things that can be done as well. (I haven't profiled the code, so that'd be my go-to check first.)
